# Site title, shown in the browser and site header
title: 🚀 Launch Calendar 🛰

# The main URL of the site
url: "https://launchcalendar.org"
# The base URL for the site (empty means root)
baseurl: ""

# URL structure for posts (year/month/day/slug)
permalink: /:year/:month/:day/:slug/

# Allow posts with future dates to be published
future: true

# Custom collections and their output settings
collections:
  launch_sites:
    output: true  # Output collection as individual pages
    permalink: /launch-sites/:path/  # URL structure for launch site pages

# Plugins to use
plugins:
  - jekyll-redirect-from
